### ISSUE TITLE
Stereo descriptors incorrectly assigned

### ISSUE THREAD

**Issue by ndedman** [chembl/chembl_beaker#11]
The stereo centres are incorreclty assigned.

Taking ephedrine as an example, the official MarvinJS webservice gives:

<img width="295" alt="screen shot 2015-08-25 at 15 02 14" src="https://cloud.githubusercontent.com/assets/6928576/9468599/6b32f654-4b3a-11e5-8c78-ff276dff64e7.png">
(the same is generated from JChem)

whereas Beaker generates:

<img width="253" alt="screen shot 2015-08-25 at 15 04 16" src="https://cloud.githubusercontent.com/assets/6928576/9468622/993b9268-4b3a-11e5-8a97-9d65e338a143.png">

The same is shown by pseudo-ephedrine ((1S,2S)-2-(methylamino)-1-phenylpropan-1-ol) which returns both stereo centres as 'R'.

**Comment by mnowotka** [comment]
Thanks Nathan, I've asked a question on the RDkit mailing list, let's see what they tell:
http://sourceforge.net/p/rdkit/mailman/message/34441037/

**Comment by mnowotka** [comment]
Fixed!
