### ISSUE TITLE
ctab2xyz: 404 Not Found Error for ctab of CHEMBL1 and others. 

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_beaker#12]
When I try to get the xyz coordinates for [CHEMBL1](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1) I get 404 not Found. 

Could it be related to the length of the url? It also happens with compounds like [CHEMBL438541](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL438541)

You can see an example [here](https://www.ebi.ac.uk/chembl/api/utils/ctab2xyz/CiAgICAgUkRLaXQgICAgICAgICAgMkQKCiA0MCA0NiAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMDk5OSBWMjAwMAogICAgMi44MzgxICAgIDQuNzYyNyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDQuNDk5NSAgICAzLjc4MzggICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0yLjY0MDggICAgNC44MTEyICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNC4zMTkzICAgIDMuODYxOSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDUuMjU0OCAgIC01LjgyOTYgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC03LjQ4MzIgICAtNC40MTc3ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy43Nzc5ICAgLTMuMjE4MyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTMuNzIxOCAgIC0zLjE1MTkgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAzLjAzOTQgICAtMS45MTI3ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMi45NjAzICAgLTEuODU5NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDYuMDM5MyAgIC0xLjkzOTIgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC01Ljk2MDIgICAtMS44MzMwICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNS4zMjM5ICAgIDEuOTY0NCAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTUuMTc1NyAgICAyLjA1NzMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA1LjI3NzggICAtMy4yMzE2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNS4yMjE3ICAgLTMuMTM4NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuODAwOSAgIC0wLjYyMDMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0zLjY5ODggICAtMC41NTM5ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy44MjM5ICAgIDEuOTc3NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTMuNjc1OCAgICAyLjA0NDAgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA1LjMwMDggICAtMC42MzM2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNS4xOTg3ICAgLTAuNTQwNiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuMDYyNCAgICAwLjY4NTMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0yLjkzNzMgICAgMC43Mzg0ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMS41NjI1ICAgIDAuNjk4NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTEuNDM3NCAgICAwLjcyNTEgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAwLjgwMTAgICAtMC41OTM4ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMC42OTg5ICAgLTAuNTgwNSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDAuODI0MCAgICAyLjAwNDIgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0wLjY3NTkgICAgMi4wMTc1ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy4wODU0ICAgIDMuMjgzMyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTIuOTE0MyAgICAzLjMzNjQgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAxLjUzOTUgICAtMS44OTk0ICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMS40NjA0ICAgLTEuODcyOCAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDYuMDE2MyAgIC00LjUzNzIgICAgMC4wMDAwIE8gICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC01Ljk4MzIgICAtNC40MzEwICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNi4wNjIzICAgIDAuNjU4NyAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTUuOTM3MiAgICAwLjc2NTAgICAgMC4wMDAwIE8gICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAxLjU4NTUgICAgMy4yOTY2ICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMS40MTQ0ICAgIDMuMzIzMSAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAxIDMxICAxICAwCiAgMiAzMSAgMSAgMAogIDMgMzIgIDEgIDAKICA0IDMyICAxICAwCiAgNSAzNSAgMSAgMAogIDYgMzYgIDEgIDAKICA3ICA5ICAyICAwCiAgNyAxNSAgMSAgMAogIDggMTAgIDEgIDAKICA4IDE2ICAyICAwCiAgOSAxNyAgMSAgMAogMTAgMTggIDIgIDAKIDExIDE1ICAyICAwCiAxMSAyMSAgMSAgMAogMTIgMTYgIDEgIDAKIDEyIDIyICAyICAwCiAxOSAxMyAgMSAgMQogMTMgMzcgIDEgIDAKIDIwIDE0ICAxICAxCiAxNCAzOCAgMSAgMAogMTUgMzUgIDEgIDAKIDE2IDM2ICAxICAwCiAxNyAyMSAgMiAgMAogMjMgMTcgIDEgIDEKIDE4IDIyICAxICAwCiAyNCAxOCAgMSAgMQogMTkgMjMgIDEgIDAKIDE5IDMxICAxICAwCiAyMCAyNCAgMSAgMAogMjAgMzIgIDEgIDAKIDIxIDM3ICAxICAwCiAyMiAzOCAgMSAgMAogMjMgMjUgIDEgIDAKIDI0IDI2ICAxICAwCiAyNSAyNyAgMSAgMAogMjUgMjkgIDIgIDAKIDI2IDI4ICAxICAwCiAyNiAzMCAgMiAgMAogMjcgMjggIDEgIDAKIDI3IDMzICAyICAwCiAyOCAzNCAgMiAgMAogMjkgMzAgIDEgIDAKIDI5IDM5ICAxICAwCiAzMCA0MCAgMSAgMAogMzEgMzkgIDEgIDAKIDMyIDQwICAxICAwCk0gIEVORAokJCQkCg==)

The ctab of CHEMBL1 is:

```

     RDKit          2D

 40 46  0  0  0  0  0  0  0  0999 V2000
    2.8381    4.7627    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4995    3.7838    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6408    4.8112    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3193    3.8619    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2548   -5.8296    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.4832   -4.4177    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7779   -3.2183    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.7218   -3.1519    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0394   -1.9127    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9603   -1.8596    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.0393   -1.9392    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.9602   -1.8330    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.3239    1.9644    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.1757    2.0573    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2778   -3.2316    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.2217   -3.1386    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8009   -0.6203    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6988   -0.5539    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8239    1.9776    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6758    2.0440    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.3008   -0.6336    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.1987   -0.5406    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0624    0.6853    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9373    0.7384    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5625    0.6986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4374    0.7251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8010   -0.5938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6989   -0.5805    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8240    2.0042    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6759    2.0175    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0854    3.2833    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9143    3.3364    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5395   -1.8994    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4604   -1.8728    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.0163   -4.5372    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.9832   -4.4310    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.0623    0.6587    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -5.9372    0.7650    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5855    3.2966    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4144    3.3231    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1 31  1  0
  2 31  1  0
  3 32  1  0
  4 32  1  0
  5 35  1  0
  6 36  1  0
  7  9  2  0
  7 15  1  0
  8 10  1  0
  8 16  2  0
  9 17  1  0
 10 18  2  0
 11 15  2  0
 11 21  1  0
 12 16  1  0
 12 22  2  0
 19 13  1  1
 13 37  1  0
 20 14  1  1
 14 38  1  0
 15 35  1  0
 16 36  1  0
 17 21  2  0
 23 17  1  1
 18 22  1  0
 24 18  1  1
 19 23  1  0
 19 31  1  0
 20 24  1  0
 20 32  1  0
 21 37  1  0
 22 38  1  0
 23 25  1  0
 24 26  1  0
 25 27  1  0
 25 29  2  0
 26 28  1  0
 26 30  2  0
 27 28  1  0
 27 33  2  0
 28 34  2  0
 29 30  1  0
 29 39  1  0
 30 40  1  0
 31 39  1  0
 32 40  1  0
M  END
$$$$
```

The full url is:

https://www.ebi.ac.uk/chembl/api/utils/ctab2xyz/CiAgICAgUkRLaXQgICAgICAgICAgMkQKCiA0MCA0NiAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMDk5OSBWMjAwMAogICAgMi44MzgxICAgIDQuNzYyNyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDQuNDk5NSAgICAzLjc4MzggICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0yLjY0MDggICAgNC44MTEyICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNC4zMTkzICAgIDMuODYxOSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDUuMjU0OCAgIC01LjgyOTYgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC03LjQ4MzIgICAtNC40MTc3ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy43Nzc5ICAgLTMuMjE4MyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTMuNzIxOCAgIC0zLjE1MTkgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAzLjAzOTQgICAtMS45MTI3ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMi45NjAzICAgLTEuODU5NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDYuMDM5MyAgIC0xLjkzOTIgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC01Ljk2MDIgICAtMS44MzMwICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNS4zMjM5ICAgIDEuOTY0NCAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTUuMTc1NyAgICAyLjA1NzMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA1LjI3NzggICAtMy4yMzE2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNS4yMjE3ICAgLTMuMTM4NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuODAwOSAgIC0wLjYyMDMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0zLjY5ODggICAtMC41NTM5ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy44MjM5ICAgIDEuOTc3NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTMuNjc1OCAgICAyLjA0NDAgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA1LjMwMDggICAtMC42MzM2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtNS4xOTg3ICAgLTAuNTQwNiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuMDYyNCAgICAwLjY4NTMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0yLjkzNzMgICAgMC43Mzg0ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMS41NjI1ICAgIDAuNjk4NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTEuNDM3NCAgICAwLjcyNTEgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAwLjgwMTAgICAtMC41OTM4ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMC42OTg5ICAgLTAuNTgwNSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDAuODI0MCAgICAyLjAwNDIgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC0wLjY3NTkgICAgMi4wMTc1ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMy4wODU0ICAgIDMuMjgzMyAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTIuOTE0MyAgICAzLjMzNjQgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAxLjUzOTUgICAtMS44OTk0ICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMS40NjA0ICAgLTEuODcyOCAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDYuMDE2MyAgIC00LjUzNzIgICAgMC4wMDAwIE8gICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIC01Ljk4MzIgICAtNC40MzEwICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNi4wNjIzICAgIDAuNjU4NyAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgLTUuOTM3MiAgICAwLjc2NTAgICAgMC4wMDAwIE8gICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICAxLjU4NTUgICAgMy4yOTY2ICAgIDAuMDAwMCBPICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAtMS40MTQ0ICAgIDMuMzIzMSAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAxIDMxICAxICAwCiAgMiAzMSAgMSAgMAogIDMgMzIgIDEgIDAKICA0IDMyICAxICAwCiAgNSAzNSAgMSAgMAogIDYgMzYgIDEgIDAKICA3ICA5ICAyICAwCiAgNyAxNSAgMSAgMAogIDggMTAgIDEgIDAKICA4IDE2ICAyICAwCiAgOSAxNyAgMSAgMAogMTAgMTggIDIgIDAKIDExIDE1ICAyICAwCiAxMSAyMSAgMSAgMAogMTIgMTYgIDEgIDAKIDEyIDIyICAyICAwCiAxOSAxMyAgMSAgMQogMTMgMzcgIDEgIDAKIDIwIDE0ICAxICAxCiAxNCAzOCAgMSAgMAogMTUgMzUgIDEgIDAKIDE2IDM2ICAxICAwCiAxNyAyMSAgMiAgMAogMjMgMTcgIDEgIDEKIDE4IDIyICAxICAwCiAyNCAxOCAgMSAgMQogMTkgMjMgIDEgIDAKIDE5IDMxICAxICAwCiAyMCAyNCAgMSAgMAogMjAgMzIgIDEgIDAKIDIxIDM3ICAxICAwCiAyMiAzOCAgMSAgMAogMjMgMjUgIDEgIDAKIDI0IDI2ICAxICAwCiAyNSAyNyAgMSAgMAogMjUgMjkgIDIgIDAKIDI2IDI4ICAxICAwCiAyNiAzMCAgMiAgMAogMjcgMjggIDEgIDAKIDI3IDMzICAyICAwCiAyOCAzNCAgMiAgMAogMjkgMzAgIDEgIDAKIDI5IDM5ICAxICAwCiAzMCA0MCAgMSAgMAogMzEgMzkgIDEgIDAKIDMyIDQwICAxICAwCk0gIEVORAokJCQkCg==

**Comment by mnowotka** [comment]
Yes, I think it can be related to the length of the url :)
For all methods where you provide molfile as in input, can you try POST instead of GET?

**Comment by nclopezo** [comment]
Ok I changed it to use POST. But in some cases it times out, for example for [CHEMBL438541](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL438541).

**Comment by mnowotka** [comment]
That's fine.
