### ISSUE TITLE
Endpoint ctab2xyz new parameter 'computeCoords'

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_beaker#15]
I'm providing a 3D SDF molfile from UFF or MMFF and this new parameter should tell the web service not to override the 3D data already provided.

Speck 3D visualiser uses ctab2xyz while LiteMol uses the 3D SDF

http://chembl-glados.herokuapp.com/compound_report_card/CHEMBL47703/

**Comment by mnowotka** [comment]
Fixed.
