### ISSUE TITLE
align and highlight issues

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_beaker#16]
Do a substructure search for Aspirin:

http://chembl-glados.herokuapp.com/substructure_search_results/CHEMBL25
change page size to 96, and go to the last page:

The following chembl Ids reply error 500 for the align call, and the highlight call returns and image, but the highlights are not present.

CHEMBL1999443, CHEMBL3264847, CHEMBL3265279, CHEMBL3265280

**Comment by mnowotka** [comment]
All the issues that could be solved without modifying rdkit code are now implemented and deployed.
