### ISSUE TITLE
Include 'sanitize' parameter support in beaker endpoints

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_beaker#17]
The 'sanitize' parameter handling is missing in the following endpoints:
- highlightCtabFragmentSvg
- smiles2SimilarityMap
- smiles2svg

**Comment by mnowotka** [comment]
I checked and all mentioned methods support the `sanitize` parameter so there have to be some deeper problem. Can you give me some example input on which each method crash or return no results?

**Comment by juanfmx2** [comment]
so here in this gist there is an example for the similarity maps:
https://gist.github.com/juanfmx2/0758d1987a5d47876757fa2fe040295e
The inclusion of the 'sanitize' parameter will give error even if it was possible to generate the similarity map without it (CHEMBL25.smi), and for the case of (CHEMBL3832892.smi) it fails both with or without the sanitize parameter.

**Comment by juanfmx2** [comment]
I updated the gist and here are the output problems:
- **smiles2SimilarityMap:** inclusion of sanitize parameter ends in error, similarity map of CHEMBL3832892 can't be created
- **smiles2svg:** svg of CHEMBL3832892 without sanitize parameter ends in error but gives empty response, and inclusion of sanitize parameter gives error
- **highlightCtabFragmentSvg:** svg of CHEMBL3832892 without sanitize parameter ends in error but gives empty response

[test_out.zip](https://github.com/chembl/chembl_beaker/files/1727692/test_out.zip)

**Comment by mnowotka** [comment]
This should be fixed now.

**Comment by juanfmx2** [comment]
it is! thanks!
