### ISSUE TITLE
Add extra formats to molExport method

### ISSUE THREAD

**Issue by ndedman** [chembl/chembl_beaker#6]
Currently we can only export in the MarvinJS native formats, i.e. .mol & .mrv.

Can we add suport for SMILES (and any others pending input!)

Cheers! :smiley:

**Comment by mnowotka** [comment]
Hi Nathan,

I've just checked and I don't think this is true (take a look at: https://github.com/chembl/chembl_beaker/blob/master/chembl_beaker/beaker/core_apps/marvin/impl.py#L82) but maybe I just don't understand something, in which case you will have to provide some more details.

**Comment by ndedman** [comment]
I think it’s on the way in:

http://www.rdkit.org/Python_Docs/rdkit.Chem.rdmolfiles-module.html#MolFromMolBlock <http://www.rdkit.org/Python_Docs/rdkit.Chem.rdmolfiles-module.html#MolFromMolBlock>

MolFromMolBlock(…)

( (AtomPairsParameters)molBlock [, (bool)sanitize=True [, (bool)removeHs=True [, (bool)strictParsing=True]]]) -> Mol

Nathan

**Comment by mnowotka** [comment]
Fixed.
