### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by mnowotka** [chembl/chembl_beaker#8]
We will need it for all our software so it's better to start with easier parts.

**Comment by eloyfelix** [comment]
RDKit is dropping Python2 support, so it would be good to go for it now.

https://github.com/rdkit/rdkit/releases/tag/Release_2019_03_1b1

**Comment by eloyfelix** [comment]
this is done in py3 branch but we'll need to wait to merge into master until we are ready to deploy it in prod
